name: teracontrol
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - pyside6
  - h5py
  - numpy
  - pyqtgraph
  - python=3.14
  - pytest
  - pyyaml
  - scipy
prefix: C:\Users\MagnetoTHz\miniconda3\envs\teracontrol
