name: teracontrol
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - numpy
  - h5py
  - pytest
  - ipykernel
  - pyqtgraph
  - pyside6
  - pyyaml
prefix: C:\Users\nickm\miniconda3\envs\teracontrol
