THz System:
  address_preset: 169.254.84.101
  address_pattern: <ip>
  addresses:
  - 169.254.84.101
  name: Toptica TeraFlash PRO
  ports:
    udp_cmd: 61234
    udp_rx: 61235
    tcp_sync: 6007
    timeout: 2.0
